export default [
  {
    avatarUrl: require("../../assets/imgs/logos/KFU.png"),
    clubId: "1",
    clubName: "نادي الحاسب بالأحساء",
    title: "بداية في علم الحاسب",
    daysLeft: "متبقي 3 أيام",
    location: "الأحساء",
    imageUrl: require("../../assets/imgs/laptop.jpg"),
    registered: false,
  },
  {
    avatarUrl: require("../../assets/imgs/logos/King_Saud_University_logo.png"),
    clubId: "2",
    clubName: "نادي الحاسب بجامعة الملك سعود",
    title: "مقدمة في علم البيانات",
    daysLeft: "متبقي 3 أيام",
    location: "الرياض",
    imageUrl: require("../../assets/imgs/Image.png"),
    registered: false,
  },
  {
    avatarUrl: require("../../assets/imgs/logos/jic.png"),
    clubId: "3",
    clubName: "نادي الحاسب بكلية الجبيل الصناعية",
    title: "مسابقة التقط العلم",
    daysLeft: "متبقي 3 أيام",
    location: "الجبيل",
    imageUrl: require("../../assets/imgs/Image.png"),
    registered: true,

  },
  {
    avatarUrl: require("../../assets/imgs/logos/KFUPM.png"),
    clubId: "4",
    clubName: "نادي الحاسب بجامعة الملك فهد للبترول و المعادن",
    title: "مقدمة في علم البيانات",
    daysLeft: "متبقي 3 أيام",
    location: "الظهران",
    imageUrl: require("../../assets/imgs/Image.png"),
    registered: true,
  },
];
