export default [
  {
    clubImage: require("../../../assets/imgs/logos/jic.png"),
    clubId: 1,
    clubTitle: "نادي الحاسب",
    clubDate: "قبل 3 أيام",
    clubMemberCount: 69,
    clubMajor: "حاسب ",
  },
  {
    clubImage: require("../../../assets/imgs/logos/jic.png"),
    clubId: 2,
    clubTitle: "النادي الرياضي ",
    clubDate: "مستمر",
    clubMemberCount: 69,
    clubMajor: "رياضي",
  },
  {
    clubImage: require("../../../assets/imgs/logos/jic.png"),
    clubId: 3,
    clubTitle: "نادي التصميم الداخلي الانهائي",
    clubDate: "قبل شهر",
    clubMemberCount: 69,
    clubMajor: "فن",
  },
  {
    clubImage: require("../../../assets/imgs/logos/jic.png"),
    clubId: 4,
    clubTitle: "نادي التصوير",
    clubDate: "قبل انفنتي أيام",
    clubMemberCount: 69,
    clubMajor: "فن",
  },
  {
    clubImage: require("../../../assets/imgs/logos/jic.png"),
    clubId: 5,
    clubTitle: "نادي التصوير",
    clubDate: "قبل انفنتي أيام",
    clubMemberCount: 69,
    clubMajor: "فن",
  },
  {
    clubImage: require("../../../assets/imgs/logos/jic.png"),
    clubId: 6,
    clubTitle: "نادي التصوير",
    clubDate: "قبل انفنتي أيام",
    clubMemberCount: 69,
    clubMajor: "فن",
  },
  {
    clubImage: require("../../../assets/imgs/logos/jic.png"),
    clubId: 7,
    clubTitle: "نادي التصوير",
    clubDate: "قبل انفنتي أيام",
    clubMemberCount: 69,
    clubMajor: "فن",
  },
];
